M48
; DRILL file {KiCad 9.0.7-9-ga3ce409f20} date 2026-03-03T19:35:03+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-03T19:35:03+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9-ga3ce409f20
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X3.5Y-3.5
X3.5Y-41.5
X41.5Y-3.5
X41.5Y-41.5
M30
