M48
; DRILL file {KiCad 9.0.7-9-ga3ce409f20} date 2026-03-28T15:52:46+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-28T15:52:46+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9-ga3ce409f20
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X106.9Y-75.3
X106.9Y-113.3
X144.9Y-75.3
X144.9Y-113.3
M30
